package uk.org.cgatechnologies.wideya.teacher_management.models

import android.os.Parcelable
import kotlinx.parcelize.Parcelize
import uk.org.cgatechnologies.wideya.common.utils.Utils
import java.util.*

@Parcelize
data class TeacherModel(
    var uuid: String = Utils.getUuidOrdered(),
    var person_uuid: String? = null,
    var full_name: String? = null,
    var last_name: String? = null,
    var middle_name: String? = null,
    var first_name: String? = null,
    var sex_oid: String? = null,
    var sex_name: String? = null,
    var date_of_birth: String? = null,
    var age: Int? = null,
    var nin: String? = null,
    var portrait_uuid: String? = null,
    var portrait_base64_data: String? = null,
    var portrait_display_orientation: Short? = 0,
    var portrait_active: Byte? = 0,
    var portrait_created_at: String? = null,
    var portrait_created_by: Int = 0,
    var phone_1: String? = null,
    var phone_2: String? = null,
    var email: String? = null,
    var address: String? = null,
    var fp_lt_uuid: String? = null,
    var fp_li_uuid: String? = null,
    var fp_rt_uuid: String? = null,
    var fp_ri_uuid: String? = null,
    var person_created_at: String? = null,
    var person_created_by: Int = 0,
    var person_updated_at: String? = null,
    var person_updated_by: Int = 0,
    var person_deleted_at: String? = null,
    var person_deleted_by: Int? = null,
    var school_uuid: String? = null,
    var school_name: String? = null,
    var employment_status_oid: String? = null,
    var employment_status_name: String? = null,
    var teacher_role_oid: String? = null,
    var teacher_role_name: String? = null,
    var teacher_role_other: String? = null,
    var pin: String? = null,
    var nassit_number: String? = null,
    var tsc_licence_id: String? = null,
    var start_date: String? = null,
    var end_date: String? = null,
    var end_reason_oid: String? = null,
    var end_reason_name: String? = null,
    var end_reason_other: String? = null,
    var end_reason_detail: String? = null,
    var created_at: String = "",
    var created_by: Int = 0,
    var updated_at: String = "",
    var updated_by: Int = 0,
    var deleted_at: String? = null,
    var deleted_by: Int? = null,
    var sync_flag: Byte = 0,
) : Parcelable