package uk.org.cgatechnologies.wideya.school_management.models

import android.os.Parcelable
import androidx.room.Ignore
import kotlinx.parcelize.IgnoredOnParcel
import kotlinx.parcelize.Parcelize
import uk.org.cgatechnologies.wideya.common.utils.Utils
import java.util.*

@Parcelize
data class LearnerAdmissionModel(
    var uuid: String = Utils.getUuidOrdered(),
    var school_uuid: String? = null,
    var school_name: String? = null,
    var learner_uuid: String? = null,
    var learner_admission_created_at: String? = null,
    var learner_admission_updated_at: String? = null,
    var learner_admission_deleted_at: String? = null,
    var learner_id: String? = null,
    var learner_created_at: String? = null,
    var learner_updated_at: String? = null,
    var learner_full_name: String? = null,
    var learner_first_name: String? = null,
    var learner_middle_name: String? = null,
    var learner_last_name: String? = null,
    var learner_nin: String? = null,
    var learner_date_of_birth: String? = null,
    var learner_age: Int? = null,
    var learner_portrait_uuid: String? = null,
    var learner_person_uuid: String? = null,
    var learner_person_created_at: String? = null,
    var learner_person_updated_at: String? = null,
    var learner_sex_oid: String? = null,
    var learner_sex_name: String? = null,
    var language_oid_strongest: String? = null,
    var language_oid_strongest_name: String? = null,
    var learner_maternal_status_oid: String? = null,
    var learner_maternal_status_name: String? = null,
    var learner_maternal_status_updated_at: String? = null,
    var learner_disability_severity_oid_vision: String? = null,
    var learner_disability_severity_oid_vision_name: String? = null,
    var learner_disability_severity_oid_hearing: String? = null,
    var learner_disability_severity_oid_hearing_name: String? = null,
    var learner_disability_severity_oid_mobility: String? = null,
    var learner_disability_severity_oid_mobility_name: String? = null,
    var learner_disability_severity_oid_cognition: String? = null,
    var learner_disability_severity_oid_cognition_name: String? = null,
    var learner_disability_severity_oid_selfcare: String? = null,
    var learner_disability_severity_oid_selfcare_name: String? = null,
    var learner_disability_severity_oid_communication: String? = null,
    var learner_disability_severity_oid_communication_name: String? = null,
    var learner_disability_other_condition_oid: String? = null,
    var learner_disability_other_condition_name: String? = null,
    var guardian_person_uuid: String? = null,
    var guardian_full_name: String? = null,
    var guardian_first_name: String? = null,
    var guardian_middle_name: String? = null,
    var guardian_last_name: String? = null,
    var guardian_nin: String? = null,
    var guardian_date_of_birth: String? = null,
    var guardian_age: Int? = null,
    var guardian_portrait_uuid: String? = null,
    var guardian_phone_1: String? = null,
    var guardian_phone_2: String? = null,
    var guardian_email: String? = null,
    var guardian_address: String? = null,
    var guardian_person_created_at: String? = null,
    var guardian_person_updated_at: String? = null,
    var guardian_sex_oid: String? = null,
    var guardian_sex_name: String? = null,
    var guardian_relation_to_learner_oid: String? = null,
    var guardian_relation_to_learner_name: String? = null,
    var guardian_relation_to_learner_other: String? = null,
    var admission_number: Int? = null,
    var start_date: String? = null,
    var end_date: String? = null,
    var end_reason_learner_oid: String? = null,
    var end_reason_learner_name: String? = null,
    var end_reason_learner_other: String? = null,
    var end_reason_learner_detail: String? = null,
    var enrolment_uuid: String? = null,
    var enrolment_current_academic_year: String? = null,
    var enrolment_current_academic_year_name: String? = null,
    var enrolment_school_group_uuid: String? = null,
    var enrolment_school_group_name: String? = null,
    var enrolment_school_group_level_oid: String? = null,
    var enrolment_school_group_level_name: String? = null,
    var enrolment_school_group_concat_name: String? = null,
    var prev_enrolment_school_group_concat_name: String? = null,
    var prev_enrolment_academic_year_name: String? = null,
    var created_at: String = "",
    var created_by: Int = 0,
    var updated_at: String = "",
    var updated_by: Int = 0,
    var deleted_at: String? = null,
    var deleted_by: Int? = null,
    var sync_flag: Byte = 0,
    var attendance_am_status_oid: String? = null,
    var attendance_pm_status_oid: String? = null,
) : Parcelable {
    @Ignore
    @IgnoredOnParcel
    var isSelected: Boolean = false
}